PREFIX w: <https://en.wikipedia.org/wiki/>

INSERT DATA
{ 
  GRAPH <https://www.wikipedia.org/> 
    {
        w:Paris w:capitalOf w:France .
        w:Berlin w:capitalOf w:Germany .
        w:Warsaw w:capitalOf w:Poland .
        w:Budapest w:capitalOf w:Hungary .
        w:Wellington w:capitalOf w:New_Zealand .
        w:London w:capitalOf w:England .
        w:Washington w:capitalOf w:United_States .
        w:Bern w:capitalOf w:Switzerland .
        w:Beijing w:capitalOf w:China .

        w:Detroit w:cityOf w:United_States .
        w:Chihuahua w:cityOf w:Mexico .
        w:Clermont w:cityOf w:France .
        w:Basel w:cityOf w:Switzerland .
        w:Pisa w:cityOf w:Italy .
        w:New_York w:cityOf w:United_States .

        w:Donald_Knuth w:nationality w:American .
        w:Ada_Lovelace w:nationality w:English .
        w:Blaise_Pascal w:nationality w:French .
        w:Leonhard_Euler w:nationality w:Swiss .

        w:American w:demonymOf w:United_States .
        w:English w:demonymOf w:England .
        w:French w:demonymOf w:France .
        w:New_Zealander w:demonymOf w:New_Zealand .
        w:Swiss w:demonymOf w:Switzerland .
        w:German w:demonymOf w:Germany .
        w:Polish w:demonymOf w:Poland .
        w:Chinese w:demonymOf w:China .

        w:Barack_Obama w:wasChiefOfState w:United_States .
        w:Charles_De_Gaulle w:wasChiefOfState w:France .
        w:Winston_Churchill w:wasChiefOfState w:England .
        w:Theodore_Roosevelt w:wasChiefOfState w:United_States .

        w:France w:phoneCode w:33 .
        w:Germany w:phoneCode w:49 .
        w:United_States w:phoneCode w:1 .
        w:Mexico w:phoneCode w:52 .
        w:Italy w:phoneCode w:39 .

        w:1 w:label_fr w:un .
        w:2 w:label_fr w:deux .
        w:3 w:label_fr w:trois .
        w:4 w:label_fr w:quatre .
        w:5 w:label_fr w:cinq .
        w:6 w:label_fr w:six .
        w:7 w:label_fr w:sept .
        w:8 w:label_fr w:huit .
        w:9 w:label_fr w:neuf .
        w:10 w:label_fr w:dix .

        w:1 w:label_en w:one .
        w:2 w:label_en w:two .
        w:3 w:label_en w:three .
        w:4 w:label_en w:four .
        w:5 w:label_en w:five .
        w:6 w:label_en w:six .
        w:7 w:label_en w:seven .
        w:8 w:label_en w:eight .
        w:9 w:label_en w:nine .
        w:10 w:label_en w:ten .

        w:1 w:label_nl w:een .
        w:2 w:label_nl w:twee .
        w:3 w:label_nl w:drie .
        w:4 w:label_nl w:vier .
        w:5 w:label_nl w:vijf .
        w:6 w:label_nl w:zes .
        w:7 w:label_nl w:zeven .
        w:8 w:label_nl w:acht .
        w:9 w:label_nl w:negen .
        w:10 w:label_nl w:tien .

        w:France w:titleOfChiefOfState w:President .
        w:Germany w:titleOfChiefOfState w:Chancellor .
        w:Poland w:titleOfChiefOfState w:President .
        w:China w:titleOfChiefOfState w:President .
        w:New_Zealand w:titleOfChiefOfState w:Prime_Minister .

        w:John_von_Neumann w:bornIn w:Budapest .
        w:Ada_Lovelace w:bornIn w:London .
        w:Blaise_Pascal w:bornIn w:Clermont .
        w:Leonhard_Euler w:bornIn w:Basel .

        w:Eiffel_Tower w:inCity w:Paris .
        w:Pisa_Tower w:inCity w:Pisa .
        w:Brandenburg_Gate w:inCity w:Berlin .
        w:Statue_of_Liberty w:inCity w:New_York .

        w:Pet_Sematary w:author w:King .
        w:1984 w:author w:Orwell .
        w:The_Lord_of_the_Rings w:author w:Tolkien .
        w:The_Da_Vinci_Code w:author w:Brown .
        w:Gulliver_s_Travels w:author w:Swift .
        w:Twilight w:author w:Meyer .
        w:Girl_with_the_Dragon_Tattoo w:author w:Larsson .
        w:Harry_Potter_and_the_Philosopher_s_Stone w:author w:Rowling .
        w:Life_of_Pi w:author w:Martel .
        w:Atonement w:author w:McEwan .

        w:FRA w:airportOf w:Frankfurt .
        w:PRG w:airportOf w:Prague .
        w:HND w:airportOf w:Tokyo .
        w:BOS w:airportOf w:Boston .
        w:DXB w:airportOf w:Dubai .
        w:LHR w:airportOf w:London .
        w:AMS w:airportOf w:Amsterdam .
        w:IST w:airportOf w:Istanbul .
        w:SIN w:airportOf w:Singapore .
        w:ATL w:airportOf w:Atlanta .


        w:China w:letters w:CN .
        w:Japan w:letters w:JP .
        w:Korea w:letters w:KR .
        w:Taiwan w:letters w:TW .
        w:Brazil w:letters w:BR .
        w:Spain w:letters w:ES .

        w:May w:label_fr w:mai .
        w:July w:label_fr w:juillet .
        w:June w:label_fr w:juin .
        w:January w:label_fr w:janvier .
        w:September w:label_fr w:septembre .
        w:December w:label_fr w:décembre .
        w:February w:label_fr w:février .
        w:October w:label_fr w:octobre .
        w:April w:label_fr w:avril .
        w:March w:label_fr w:mars .

        w:Guernica w:author w:Picasso .
        w:Girl_with_a_Pearl_Earring w:author w:Vermeer .
        w:Broadway_Boogie-Woogie w:author w:Mondrian .
        w:The_Scream w:author w:Munch .
        w:The_Kiss w:author w:Klimt .
        w:The_Birth_of_Venus w:author w:Botticelli .
        w:Nighthawks w:author w:Hopper .
        w:The_Persistence_of_Memory w:author w:Dalí .
        w:The_Night_Watch w:author w:Rembrandt .

        w:United_States w:currency w:USD .
        w:Japan w:currency w:JPY .
        w:European_Union w:currency w:EUR .
        w:United_Kingdom w:currency w:GBP .
        w:Autralia w:currency w:AUD .
        w:Canada w:currency w:CAD .
        w:Sweden w:currency w:SEK .
        w:Czechia w:currency w:CZK .
        w:China w:currency w:CNY .
        w:South_Kora w:currency w:KRW .

        w:March w:number w:03 .
        w:February w:number w:02 .
        w:November w:number w:11 .
        w:December w:number w:28 .
        w:August w:number w:08 .

  }
};
INSERT
{ 
  ?country w:demonym ?dem .
}
WHERE { 
  ?dem w:demonymOf ?country . 
};
INSERT
{ 
  ?city w:cityOf ?country .
  ?country w:isCapitalOf ?city .
}
WHERE { 
  ?city w:capitalOf ?country . 
};
INSERT
{ 
  ?country w:contains ?city .
}
WHERE { 
  ?city w:cityOf ?country . 
};
INSERT
{ 
  ?l w:number ?n .
}
WHERE { 
  ?n w:label_en ?l . 
};
INSERT
{ 
  ?l w:number ?n .
  # Some non coherent relations since we also need the correspondance between months
}
WHERE { 
  ?n w:label_fr ?l . 
};
INSERT
{ 
  ?l w:number ?n .
}
WHERE { 
  ?n w:label_nl ?l . 
};

INSERT
{ 
  ?cur w:currencyOf ?c .
}
WHERE { 
  ?c w:currency ?cur . 
};
INSERT
{ 
  ?n w:toMonth ?m .
}
WHERE { 
  ?m w:number ?n . 
};